allowBuilds:
  better-sqlite3: true
  better-sqlite3-multiple-ciphers: true
  electron: true
  electron-winstaller: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@capacitor/android@8.5.2'
  - '@capacitor/core@8.5.2'
  - '@capacitor/cli@8.5.2'
