import type { TranslationKey } from "./zh-CN";

export const enUS: Record<TranslationKey, string> = {
  "language.label": "Language",
  "language.zh-CN": "简体中文",
  "language.en-US": "English",
  "language.systemHint": "Ling selected this from your device language. You can change it at any time.",
  "language.settingsHint": "The interface, professional information, and new sessions will use this language. Active sessions and existing content keep their original language and are not translated automatically.",

  "brand.studio": "Qunxin Psychology Studio",
  "brand.copyright": "© 2026 Ling-Team",
  "launch.sceneLabel": "The waiting room of Qunxin Psychology Studio, seen from a lakeside porch",
  "launch.welcome.progress": "01 / 03",
  "launch.welcome.progressLabel": "Step 1 of 3",
  "launch.welcome.title": "Welcome to Qunxin Psychology Studio",
  "launch.welcome.description": "Three AI counselors are here to support emotional reflection, self-exploration, and ongoing counseling-style conversations.",
  "launch.welcome.nameLabel": "How would you like us to address you?",
  "launch.welcome.namePlaceholder": "Enter a name or nickname you use",
  "launch.welcome.nameHint": "Use any name or nickname that feels comfortable. It will be shared with the three AI counselors; you can also leave it blank or change it later.",
  "launch.welcome.actionsLabel": "Welcome actions",
  "launch.welcome.continue": "Continue",

  "launch.security.progressLabel": "Step 3 of 3",
  "launch.security.kicker": "Data security",
  "launch.security.actionsLabel": "Data security actions",
  "common.back": "Back",
  "common.continue": "Continue",
  "messages.copy": "Copy",

  "reception.name": "Counselor on duty",
  "reception.role": "Counselor",
  "reception.dialogueLabel": "Reception conversation with a counselor",
  "reception.scenePortraitAlt": "Counselor on duty behind the reception desk",
  "reception.dialoguePortraitAlt": "Counselor portrait in conversation",
  "reception.showFull": "Show the full dialogue",
  "reception.options": "Reception options",
  "reception.book": "I'd like to book a counseling session",
  "reception.tour": "Please show me around the studio",
  "reception.smallTalk": "Let's chat for a bit",
  "reception.smallTalk.more": "Keep chatting",
  "reception.smallTalk.done": "Let's stop here, thank you",
  "reception.browse": "I'll look around on my own",
  "reception.notNow": "Not right now, thank you",

  "booking.with": "Begin counseling with {name}",
  "booking.activeTitle": "You still have an unfinished session",
  "booking.draftTitle": "This session has not formally begun",
  "booking.activeBody": "You can continue the earlier session, or let it move into closing preparation and begin a new one.",
  "booking.draftBody": "This session has not formally begun. You can continue into the room, or cancel and return to counselor selection.",
  "booking.continuePrevious": "Continue the earlier session",
  "booking.startNew": "Begin a new session",
  "booking.backCounselors": "Back to counselor selection",
  "booking.cancel": "Cancel this session",
  "booking.enterRoom": "Continue to the counseling room",
  "booking.preparing": "Preparing the counseling room",
  "booking.preparingBody": "Ling is saving this session and loading the counselor's setting and materials. The opening will begin when it is ready.",
  "booking.createError": "This session could not be created. Please try again.",

  "common.counselor": "Counselor",
  "settings.title": "Settings",
  "lobby.waitingRoom": "Qunxin Psychology Studio · Waiting room",
  "lobby.consentArchive": "AI counseling informed consent",
  "lobby.closeConsentPreview": "Close informed-consent preview",
  "lobby.consentTitle": "AI Counseling Informed Consent",
  "lobby.consentKeyPoints": "Key information about AI counseling",
  "lobby.closeConsent": "Close AI counseling information",
  "lobby.modelArchive": "Model connection before counseling",
  "lobby.notStart": "Do not begin counseling yet",
  "lobby.bookingArchive": "Booking in progress",
  "lobby.closePreparation": "Close counseling preparation",

  "features.bookcase.archive": "Studio reading archive",
  "features.bookcase.close": "Close storybook",
  "features.bookcase.title": "Stories",
  "features.resources.archive": "Studio resource archive",
  "features.resources.close": "Close Resources Desk",
  "features.resources.title": "Guidance & Support Resources",
  "features.photo.archive": "Studio photo archive",
  "features.photo.close": "Close studio album",
  "features.photo.title": "Studio Album",
  "features.counselors.archive": "Qunxin Psychology Studio counselor archive",
  "features.counselors.close": "Close counselor introductions",
  "features.counselors.title": "Meet the Counselors",
  "features.booking.title": "Book a Session",
  "features.letters.archive": "Private counselor-letter archive",
  "features.letters.close": "Close letters",
  "features.letters.title": "Letters from Your Counselors",
  "features.records.archive": "Private session archive",
  "features.records.close": "Close session records",
  "features.records.title": "Session Records",

  "hotspot.receptionAria": "Go to reception and speak with the counselor on duty",
  "hotspot.reception": "Reception",
  "hotspot.bookcaseAria": "Open the storybook on the bookcase",
  "hotspot.bookcase": "Bookcase",
  "hotspot.photoAria": "View the studio group photo",
  "hotspot.photo": "Album",
  "hotspot.gardenAria": "Go to the garden outside the window",
  "hotspot.garden": "Garden",
  "hotspot.resourcesAria": "View guidance and support resources",
  "hotspot.resources": "Resources",
  "hotspot.recordsAria": "View session records beside the sofa",
  "hotspot.records": "Records",
  "hotspot.meetCounselor": "Meet {name}",
  "quickNav.aria": "Waiting-room shortcuts",

  "photo.heading": "A photo of the three counselors",
  "photo.subheading": "An ordinary moment with Cheng Ling, Zhou Zhou, and Lin Leshui at the studio",
  "photo.altOverhead": "Three women counselors sit around a round table, one explaining with an open hand, one making a peace sign, and one holding a teacup",
  "photo.altTea": "Three women counselors sit side by side at a tea table, with a teapot, teacups, and a small vase of flowers",
  "photo.altHuddle": "Three women counselors smile shoulder to shoulder at the camera, with the woman on the left waving and the woman on the right making a hand gesture",
  "photo.previous": "Previous group photo",
  "photo.next": "Next group photo",
  "photo.current": "Current photo",
  "photo.selectorLabel": "Choose a group photo",
  "photo.showOverhead": "Show the overhead table photo",
  "photo.showTea": "Show the afternoon tea photo",
  "photo.showHuddle": "Show the shoulder-to-shoulder photo",
  "photo.caption": "Qunxin Psychology Studio · Counselor photo",
  "photo.descriptionLabel": "About this photo",
  "photo.kicker": "That afternoon",
  "photo.copyTitle": "All three, for once, in the frame",
  "photo.copy1": "The studio had just been tidied and the afternoon light was good. Someone pressed the shutter and kept the moment.",
  "photo.copy2": "They usually work in separate rooms, so it was unusual to find them sitting together. There was no particular occasion—just an ordinary afternoon they happened to enjoy.",
  "photo.footer": "An ordinary afternoon",

  "garden.title": "Lakeside Garden",
  "garden.back": "Back to the waiting room",
  "garden.switchSunny": "Change to sunny weather",
  "garden.switchRainy": "Change to rain",
  "garden.sunny": "Sunny",
  "garden.rainy": "Rain",
  "garden.rainHeading": "As the rain falls, the world slows a little.",
  "garden.sunHeading": "A breeze crosses the lake and moves softly through the leaves.",
  "garden.future": "Music, breathing, and brief settling practices will be added here in the future.",
  "garden.breathingIntro": "There is no need to count. Follow the changing light and let the breath move naturally in and out.",
  "garden.startBreathing": "Begin breathing",

  "startup.aria": "Ling is starting",
  "startup.logoAlt": "Qunxin three-person boat",
  "startup.restoreError": "Ling could not read the sessions stored on this device. Existing information was not changed. Please try again.",
  "startup.restoreErrorAria": "Ling could not read local information",
  "startup.restoreErrorTitle": "Your local sessions could not be loaded",
  "startup.retry": "Try again",
  "startup.restoringAria": "Ling is reading information stored on this device",
  "startup.restoring": "Loading local sessions…",

  "lock.aria": "Ling password protection",
  "lock.welcome": "Welcome back",
  "lock.resetTitle": "Reset your password with a recovery code",
  "lock.passwordBody": "Password protection is enabled on this device. Enter your password to continue to your sessions and reading.",
  "lock.password": "Password",
  "lock.opening": "Opening…",
  "lock.enter": "Enter Ling",
  "lock.forgot": "Forgot your password? Use the recovery code",
  "lock.recoveryBody": "Enter the recovery code you saved when enabling password protection. After it is verified, you can set a new password.",
  "lock.recoveryCode": "Recovery code",
  "lock.recoveryCodePlaceholder": "Enter the recovery code",
  "lock.newPassword": "New password",
  "lock.confirmPassword": "Enter the new password again",
  "lock.checking": "Verifying…",
  "lock.verifyAndSet": "Verify and set new password",
  "lock.back": "Back to password entry",
  "lock.verifyError": "Your password could not be verified just now. Please try again.",
  "lock.passwordMismatch": "The two new passwords do not match.",
  "lock.recoveryError": "Your password could not be recovered just now. Please try again.",

  "settings.archive": "Ling settings",
  "settings.close": "Close settings",
  "settings.exit": "Return to the studio",
  "settings.aria": "Ling settings",
  "settings.logoAlt": "Qunxin Psychology Studio logo",
  "settings.brandLine": "SETTINGS · QUNXIN PSYCHOLOGY STUDIO",
  "settings.unsavedTitle": "You have unsaved settings",
  "settings.unsavedBody": "This page contains unsaved changes. If you continue, those changes will be discarded and the most recently saved values restored.",
  "settings.discard": "Discard changes and continue",
  "settings.return": "Return to this page",

  "room.you": "You",
  "room.noSession": "No session yet",
  "room.unfinishedBlocked": "There is another unfinished session with this counselor. Continue or end it first.",
  "room.olderReadOnly": "Only the most recently ended session with this counselor can be continued. Earlier sessions remain available as read-only records.",
  "room.closingNotice": "After the session, I will put what I want to leave with you into a letter under “Letters from your counselors” in the waiting-room bar. The complete session remains available under “Session records” by the sofa.",
  "room.statusOther": "{name} is responding in another session",
  "room.statusThinking": "{name} is thinking",
  "room.statusSpeaking": "{name} is responding",
  "room.statusListening": "{name} is listening",
  "room.statusError": "The connection was interrupted. Check Settings.",
  "room.attachmentEmpty": "No text could be read from {file}. Remove it or choose another file before sending.",
  "room.attachmentReadError": "The attachment could not be read. Choose it again, or remove it before sending.",
  "room.attachmentUnsupported": "{file} uses an unsupported format. Choose an image, TXT, Markdown, PDF, DOC, or DOCX file. PDFs and Word files are currently saved as file records without reading their contents.",
  "room.attachmentTooLarge": "{file} is larger than 50 MB and cannot be added. Choose a smaller file.",
  "room.pastedFileName": "pasted-long-text.txt",
  "room.pasteNotice": "The pasted text, about {count} characters, was converted into a text resource. You can remove it before sending.",
  "room.start": "Begin counseling",
  "room.backLobby": "Back to the waiting room",
  "room.skipOpening": "Skip the opening",
  "room.enterDirectly": "Enter the session",
  "room.skipClosing": "Skip the closing",
  "room.letterOpened": "Your letter is open",
  "room.letterUnknown": "Ling cannot confirm whether this letter is complete.",
  "room.reloadStatus": "Reload status",
  "room.backPrevious": "Back",
  "room.aria": "{name}'s counseling room",
  "room.closeError": "Close counseling error",
  "room.loadingMessages": "Ling is loading the complete session record. No new message will be sent until loading finishes.",
  "room.reload": "Reload",
  "room.continueCurrent": "Continue this session",
  "room.confirmEnd": "End session",
  "room.endMessage": "The session will end and become read-only, so no more messages can be sent. Ling will organize the session in the background and prepare a counselor letter. The complete record will remain under “Session records” in the waiting room.",
  "room.endTitle": "End this session?",
  "room.returnCheck": "Go back and review",
  "room.clearAndStart": "Clear and begin a new session",
  "room.endAndStart": "End this session and create a new one",
  "room.newUnsentMessage": "Nothing has been sent in this session. Beginning a new one will clear the unsent text and attachments, and this empty session will not be kept.",
  "room.newMixedMessage": "This session will end and enter background preparation. Sent content will be kept; unsent text and attachments will not.",
  "room.newSentMessage": "This session will end and enter background preparation. Sent session content will be kept.",
  "room.newTitle": "Begin a new session?",

  "composer.pendingAttachments": "Attachments waiting to be sent",
  "composer.removeAttachment": "Remove attachment {name}",
  "composer.chooseFile": "Choose attachment files",
  "composer.addAttachment": "Add an attachment",
  "composer.attachmentHelp": "Choose a photo, document, or text file",
  "composer.voice.startInput": "Start voice input",
  "composer.voice.stopInput": "Stop voice input",
  "composer.voice.title": "Voice input",
  "composer.voice.stopDictation": "Stop dictation",
  "composer.voice.shortcutHint": "{shortcut} · Press once to start or stop",
  "composer.voice.clickHint": "Click to begin · Add a shortcut in Settings",
  "composer.input": "Session message",
  "composer.endedPlaceholder": "This session has ended. Choose “Continue session” before writing another message.",
  "composer.placeholder": "Take your time. What's happening?",
  "composer.ended": "Ended",
  "composer.wait": "Wait",
  "composer.stop": "Stop",
  "composer.send": "Send",

  "messages.stream": "Messages",
  "messages.startNew": "Begin a new session",
  "messages.avatar": "{name}'s avatar",
  "messages.responding": "{name} is responding",
  "messages.attachments": "Message attachments",
  "messages.imageSent": "Sent to the model for recognition",
  "messages.notRead": "Content not read",
  "messages.characterCount": "About {count} characters",
  "messages.understanding": "{name} is taking in what you said",
  "messages.sendFailed": "Sending did not finish",
  "messages.retry": "Retry",

  "preparation.aria": "Post-session preparation progress",
  "preparation.heading": "After-session preparation",
  "preparation.failed": "Not completed",
  "preparation.working": "Preparing",
  "preparation.failedBody": "This preparation did not complete. You can generate it again.",
  "preparation.workingBody": "Ling is organizing this session and preparing the counselor's letter. You can return to the waiting room; processing will continue.",
  "preparation.retry": "Prepare this session again",

  "letter.cardAria": "Letter from your counselor",
  "letter.from": "A letter from {name}",
  "letter.ready": "Ready",
  "letter.failed": "Generation failed",
  "letter.writing": "Being written",
  "letter.pendingBody": "{name} is writing your letter. You can return to the waiting room; when ready, it will appear under “Letters from your counselors.”",
  "letter.failedBody": "This letter did not finish. You can generate it again later.",
  "letter.readyBody": "Your letter is ready. You can open it now or read it later.",
  "letter.progress": "Your counselor is writing; this usually takes 1–3 minutes",
  "letter.open": "Open this letter",
  "letter.regenerate": "Generate again",
  "letter.readerAria": "A letter to you from {name}",
  "letter.close": "Close letter",
  "letter.title": "A letter to you from {name}",

  "history.current": "Current session",
  "history.endingAria": "Ending counseling session",
  "history.with": "Session with {name}",
  "history.recheck": "Check status again",
  "history.resume": "Continue session",
  "history.endingStatus": "Saving the session and confirming that it ended. Please wait…",
  "history.loading": "Ling is loading the complete session record. If this takes a long time, you can reload it.",
  "history.reload": "Reload session record",

  "sidebar.roomActions": "Counseling-room actions",
  "sidebar.returnHint": "This session will be kept so you can continue later.",
  "sidebar.continueSession": "Continue this session",
  "sidebar.endSession": "End this session",
  "sidebar.end": "End",
  "sidebar.continueHint": "Return to this session and continue the conversation.",
  "sidebar.endHint": "The session record will be kept and your counselor will prepare a letter.",
  "stage.currentInfo": "Current session information",
  "closing.options": "Options after the session ends",
  "closing.viewHistory": "View session record",
  "closing.readLetter": "Read counselor letter",
  "closing.resume": "Continue this session",
  "arrival.aria": "Entering the counseling room",
  "arrival.continue": "Continue into the counseling room",
  "arrival.showFull": "Show the complete arrival card",
  "confirm.stay": "Stay here",
  "dialogue.next": "Next",
  "dialogue.opening": "Counseling opening",
  "dialogue.closing": "Counseling closing",
  "dialogue.counselor": "Counselor",
  "dialogue.wait": "Please wait…",
  "counselors.portraitAlt": "Portrait of counselor {name}",

  "session.ended": "Ended",
  "session.active": "In progress",
  "session.deleteConfirm": "Delete “{title}”? This removes the session record from this device and cannot be undone.",
  "session.navigation": "Session navigation",
  "session.tools": "Session tools",
  "session.newAria": "End this session and begin a new one with this counselor",
  "session.new": "New session",
  "session.newHint": "End this session and begin another",
  "session.recordsHint": "View the current and earlier sessions",
  "session.settingsHint": "Adjust the model and your preferences",
  "session.settings": "Settings",
  "session.localSessions": "Local sessions",
  "session.localSaved": "Saved locally",
  "session.closeRecords": "Close session records",
  "session.noCurrent": "There is no active session with this counselor.",
  "session.historyCount": "Earlier sessions ({count})",
  "session.searchAria": "Search earlier sessions with this counselor",
  "session.searchPlaceholder": "Search earlier sessions with this counselor",
  "session.noOther": "There are no other sessions with this counselor yet",
  "session.noMatch": "No matching earlier session was found",
  "session.rename": "Rename",
  "session.renameInput": "Rename session",
  "session.delete": "Delete",
  "session.actions": "Actions for session {title}",
  "session.deleteAria": "Delete session {title}",

  "launch.model.progressLabel": "Step 2 of 3",
  "launch.model.kicker": "Model connection",
  "launch.model.title": "Connect a model service",
  "launch.model.intro": "Use an API service or connect a model running on this device.",
  "launch.model.guideTitle": "How do I get an API key?",
  "launch.model.guideBody": "Sign up or sign in to the DeepSeek Platform, open “API Keys,” create a key, then paste it below.",
  "launch.model.openKeys": "Open DeepSeek API Keys",
  "launch.model.keyPlaceholder": "Paste an API key beginning with sk-",
  "launch.model.show": "Show",
  "launch.model.hide": "Hide",
  "launch.model.configuredNote": "DeepSeek's official endpoint and the recommended DeepSeek V4 Flash configuration are already selected.",
  "launch.model.actionsLabel": "Model connection actions",
  "launch.model.connecting": "Connecting…",
  "launch.model.connect": "Connect and continue",
  "launch.model.skip": "Skip for now",

  "settings.profile.languageTitle": "Interface and counseling language",
  "settings.profile.languageDescription": "Changes take effect immediately and are saved on this device.",
  "settings.profile.save": "Save profile",

  "update.noticeLabel": "Ling update available",
  "update.dismiss": "Dismiss update notice",
  "update.availableSuffix": "is available",
  "update.manualInstall": "Download it from the official website and install it when you are ready.",
  "update.openWebsite": "Open official download page",

  "consent.fullTitle": "Full informed-consent document",
  "consent.beforeCounseling": "Before counseling",
  "consent.headerDescription": "This introduction and all the sections use the same content kept on the Resources Desk. Read at your own pace, then decide whether to continue.",
  "consent.readingDirectory": "Contents",
  "consent.overview": "Introduction",
  "consent.startingInformation": "Before you begin",
  "consent.readingInformation": "Reading information",
  "consent.introductionTitle": "Before you begin, please understand this AI counseling relationship in full",
  "consent.introductionAside": "Use the contents on the left to read each section. You may stop here at any time. The same complete document will remain available on the Resources Desk.",
  "consent.resourceIntroTitle": "Reading information and contents",
  "consent.directoryLabel": "Sections of the full informed-consent document",
  "consent.previous": "Previous",
  "consent.next": "Next",
  "consent.version": "Version",
  "consent.notNow": "Not now",
  "consent.agree": "Agree and enter counseling",
  "consent.acknowledgement": "I have read and understood this full informed-consent document. I understand that Ling provides counseling based on AI large language models and cannot replace counseling by a qualified human professional, psychotherapy, psychiatric care, or crisis response. I may choose not to enter and may leave at any time. I choose to continue.",
  "consent.sensitiveAcknowledgement": "I understand that in the official version of Ling, session records are stored on this device by default and are not transmitted through Ling-operated servers. When I use a local model, the relevant content stays on this device. When I use a third-party model API, content needed to generate responses and post-session materials is sent to the model provider I configure and is handled under that provider's privacy policy. I agree to this processing as described above.",

  "crisis.title": "Crisis & Safety Support",
  "crisis.directory": "Crisis and safety support contents",
  "crisis.directoryLabel": "On this page",
  "crisis.immediateTitle": "If you are afraid that you or someone else may be harmed now",
  "crisis.immediateBody": "Tell a trusted person where you are now and contact the emergency service for your location. In mainland China, call 110 or 120. If you cannot call, ask someone nearby to call or accompany you to the nearest emergency department. Do not wait for Ling or a crisis line to respond.",
  "crisis.emergencyNumbers": "Emergency numbers in mainland China",
  "crisis.situationsTitle": "If this moment feels very hard to endure",
  "crisis.situationsIntro": "These actions are only for connecting with and waiting for real-world help; they do not replace emergency response. You do not have to do all of them. If danger is happening now, return to the previous page and contact emergency services.",
  "crisis.moreActions": "More options",
  "crisis.contactsTitle": "Mainland China | Support resources",
  "crisis.contactsNote": "Selecting a number here does not place a call. Ling cannot call, locate you, contact police, or dispatch help. Use a phone or another device to contact the service yourself.",
  "crisis.noAnswerTitle": "If no one answers, or danger is increasing",
  "crisis.noAnswerBody": "Do not keep waiting for a psychological assistance line. Call 110 or 120 in mainland China, ask someone nearby to call, or ask someone to accompany you to the nearest emergency department; do not drive yourself. A psychological assistance line provides human support but is not the same as on-site emergency response.",
  "crisis.otherRegionsTitle": "If you are outside mainland China",
  "crisis.otherRegionsBody": "Contact your local emergency number, crisis line, or nearest emergency department. If you are unsure which service applies, ask a trusted person nearby to help you find and contact it. Choosing English does not mean that the mainland China numbers below will work where you are.",
  "crisis.officialSource": "Read the National Health Commission notice about 12356",
  "crisis.limitTitle": "Do not rely on Ling as an emergency service",
  "crisis.limitBody": "Ling cannot continuously monitor whether you are safe or disconnected. It cannot confirm your location, place a call, contact police, notify family or friends, or dispatch help. If there is danger, do not wait for an AI response. Contact a person in your life, local emergency services, or the nearest emergency department directly.",
  "crisis.limitEmergencyBody": "A crisis line, text support, breathing, or grounding cannot replace emergency services or an emergency department. A reply from Ling is not a professional risk assessment.",

  "counselors.choose": "Choose a counselor",
  "counselors.currentlyViewing": "Viewing",
  "counselors.activeSession": "Session in progress",
  "counselors.book": "Book a session",
  "counselors.aiBoundaryLabel": "About this AI counselor",
  "counselors.aiBoundary": "She is an AI counselor who can offer psychological support. She cannot replace qualified counseling, psychiatric care, medical diagnosis, or crisis intervention.",
  "counselors.viewHeading": "How she understands counseling",
  "counselors.workingHeading": "How she works with people",
  "counselors.topicsHeading": "Topics she often explores",
  "counselors.sharedBeliefTitle": "A belief shared by Ling counselors",
  "counselors.sharedBelief1": "A counselor is not the keeper of answers, but a mirror.",
  "counselors.sharedBelief2": "Counseling is not a search outside yourself for a ready-made answer.",
  "counselors.sharedBelief3": "It is a shared exploration of what has not yet been seen or understood within, allowing self-understanding to grow over time.",

  "resources.back": "Back to resources",
  "resources.documentVersion": "Document version",
  "resources.version": "Version",
  "resources.loading": "Opening resource…",
  "resources.empty": "There is no content to display in this resource.",
  "resources.error": "This resource could not be opened. Please try again.",
  "resources.desk": "Resources Desk",
  "resources.studioMaterials": "Studio resources",
  "resources.footer": "Using Ling · Safety support · Informed consent",
  "resources.view": "View",

  "guide.title": "Using Ling",
  "guide.directory": "Using Ling contents",
  "guide.topicLabel": "Using Ling · Read what you need",
  "guide.note": "Additional information",
  "guide.return": "Back to Using Ling contents"
};
