export const zhCN = {
  "language.label": "语言",
  "language.zh-CN": "简体中文",
  "language.en-US": "English",
  "language.systemHint": "已根据这台设备的系统语言为你选择，可随时更改。",
  "language.settingsHint": "界面、专业说明和新建会谈会使用所选语言。进行中的会谈与已有内容会保留原语言，不会被自动翻译。",

  "brand.studio": "群心心理工作室",
  "brand.copyright": "© 2026 Ling-Team",
  "launch.sceneLabel": "从湖边门廊望进群心心理工作室的等待室",
  "launch.welcome.progress": "01 / 03",
  "launch.welcome.progressLabel": "引导第一步，共三步",
  "launch.welcome.title": "欢迎来到群心心理工作室",
  "launch.welcome.description": "这里有三位 AI 心理咨询师，陪你进行情绪支持、自我探索和连续的咨询式对话。",
  "launch.welcome.nameLabel": "你希望我们怎么称呼你？",
  "launch.welcome.namePlaceholder": "填写名字、昵称或你习惯的称呼",
  "launch.welcome.nameHint": "名字、昵称，或任何让你自在的称呼都可以。它会提供给三位 AI 咨询师；也可以留空，之后再修改。",
  "launch.welcome.actionsLabel": "欢迎页操作",
  "launch.welcome.continue": "继续",

  "launch.security.progressLabel": "引导第三步，共三步",
  "launch.security.kicker": "数据安全",
  "launch.security.actionsLabel": "数据安全设置操作",
  "common.back": "返回",
  "common.continue": "继续",
  "messages.copy": "复制",

  "reception.name": "值班咨询师",
  "reception.role": "咨询师",
  "reception.dialogueLabel": "咨询师的前台对话",
  "reception.scenePortraitAlt": "值班咨询师在前台后",
  "reception.dialoguePortraitAlt": "咨询师对话立绘",
  "reception.showFull": "显示完整对白",
  "reception.options": "接待选项",
  "reception.book": "我想预约心理咨询",
  "reception.tour": "请带我看看工作室",
  "reception.smallTalk": "随便聊聊",
  "reception.smallTalk.more": "再多聊聊",
  "reception.smallTalk.done": "先聊到这，谢谢",
  "reception.browse": "我先自己看看",
  "reception.notNow": "暂时不用，谢谢",

  "booking.with": "与{name}开始咨询",
  "booking.activeTitle": "你还有一次尚未结束的咨询",
  "booking.draftTitle": "这次咨询还没有正式开始",
  "booking.activeBody": "你可以继续之前的咨询，也可以让它进入收尾整理，再开始一次新咨询。",
  "booking.draftBody": "这次咨询还没有正式开始。你可以继续进入，也可以取消并返回选择。",
  "booking.continuePrevious": "继续之前的咨询",
  "booking.startNew": "开启新咨询",
  "booking.backCounselors": "返回选择咨询师",
  "booking.cancel": "取消这次咨询",
  "booking.enterRoom": "继续进入咨询室",
  "booking.preparing": "正在准备咨询室",
  "booking.preparingBody": "正在保存这次咨询，并加载咨询师所需的场景与资料。完成后会进入咨询开场。",
  "booking.createError": "没有创建这次咨询，请重试。",

  "common.counselor": "咨询师",
  "settings.title": "系统设置",
  "lobby.waitingRoom": "群心心理工作室 · 等待室",
  "lobby.consentArchive": "AI 咨询知情说明",
  "lobby.closeConsentPreview": "关闭知情同意预览",
  "lobby.consentTitle": "AI 咨询知情说明",
  "lobby.consentKeyPoints": "AI 咨询重点说明",
  "lobby.closeConsent": "关闭 AI 咨询说明",
  "lobby.modelArchive": "咨询前模型连接",
  "lobby.notStart": "暂不开始咨询",
  "lobby.bookingArchive": "预约处理中",
  "lobby.closePreparation": "关闭咨询准备",

  "features.bookcase.archive": "工作室阅读档案",
  "features.bookcase.close": "关闭故事簿",
  "features.bookcase.title": "故事簿",
  "features.resources.archive": "工作室资料档案",
  "features.resources.close": "关闭资料桌",
  "features.resources.title": "使用说明与自助资料",
  "features.photo.archive": "工作室影像档案",
  "features.photo.close": "关闭工作室相册",
  "features.photo.title": "工作室相册",
  "features.counselors.archive": "群心心理工作室咨询师档案",
  "features.counselors.close": "关闭咨询师介绍",
  "features.counselors.title": "咨询师介绍",
  "features.booking.title": "预约咨询",
  "features.letters.archive": "工作室私人来信档案",
  "features.letters.close": "关闭来信",
  "features.letters.title": "咨询师的信",
  "features.records.archive": "工作室私人会谈档案",
  "features.records.close": "关闭会谈记录",
  "features.records.title": "会谈记录",

  "hotspot.receptionAria": "前往前台，与值班咨询师交谈",
  "hotspot.reception": "前台",
  "hotspot.bookcaseAria": "打开书架故事簿",
  "hotspot.bookcase": "书架",
  "hotspot.photoAria": "查看工作室合照",
  "hotspot.photo": "相册",
  "hotspot.gardenAria": "前往窗外花园",
  "hotspot.garden": "花园",
  "hotspot.resourcesAria": "查看使用说明与自助资料",
  "hotspot.resources": "资料桌",
  "hotspot.recordsAria": "在沙发区查看会谈记录",
  "hotspot.records": "会谈记录",
  "hotspot.meetCounselor": "认识{name}",
  "quickNav.aria": "等待室快捷入口",

  "photo.heading": "三位咨询师的合照",
  "photo.subheading": "程灵、周舟和林乐水在工作室的一次日常留影",
  "photo.altOverhead": "三位女性咨询师围坐在圆桌旁交流，一人举手讲解，一人比出手势，另一人端着茶杯",
  "photo.altTea": "三位女性咨询师并排坐在茶桌旁交谈，桌上摆着茶壶、茶杯和一瓶小花",
  "photo.altHuddle": "三位女性咨询师肩并肩面对镜头微笑，左侧挥手，右侧做出手势",
  "photo.previous": "上一张合照",
  "photo.next": "下一张合照",
  "photo.current": "当前照片",
  "photo.selectorLabel": "选择合照",
  "photo.showOverhead": "查看俯拍围桌合照",
  "photo.showTea": "查看下午茶合照",
  "photo.showHuddle": "查看肩靠肩合照",
  "photo.caption": "群心心理工作室 · 咨询师合照",
  "photo.descriptionLabel": "合照说明",
  "photo.kicker": "那天下午",
  "photo.copyTitle": "难得都在镜头里",
  "photo.copy1": "整理完工作室，阳光正好。有人顺手按下快门，留下了这一刻。",
  "photo.copy2": "平时，她们各自在不同的房间里工作，难得这样坐到一起。没有特别的缘由，只是一个普通、也让人喜欢的下午。",
  "photo.footer": "一个普通的下午",

  "garden.title": "湖畔花园",
  "garden.back": "返回等待室",
  "garden.switchSunny": "切换为晴天",
  "garden.switchRainy": "切换为雨天",
  "garden.sunny": "晴天",
  "garden.rainy": "雨天",
  "garden.rainHeading": "雨落下来，世界慢了一点。",
  "garden.sunHeading": "风从湖面过来，花叶轻轻响。",
  "garden.future": "以后，这里会加入音乐、呼吸和短暂安顿自己的练习。",
  "garden.breathingIntro": "不用数拍子，只跟着光的起伏，自然地吸气、呼气。",
  "garden.startBreathing": "开始呼吸",

  "startup.aria": "Ling 启动中",
  "startup.logoAlt": "群心三人舟",
  "startup.restoreError": "没有成功读取本机会谈。现有资料没有被修改，请重新读取。",
  "startup.restoreErrorAria": "Ling 本机资料读取失败",
  "startup.restoreErrorTitle": "没有读取到本机会谈",
  "startup.retry": "重新读取",
  "startup.restoringAria": "正在读取 Ling 本机资料",
  "startup.restoring": "正在读取本机会谈……",

  "lock.aria": "Ling 密码保护",
  "lock.welcome": "欢迎回来",
  "lock.resetTitle": "用恢复码重设密码",
  "lock.passwordBody": "这台设备已开启密码保护。输入密码后，继续你的会谈与阅读。",
  "lock.password": "密码",
  "lock.opening": "正在打开……",
  "lock.enter": "进入 Ling",
  "lock.forgot": "忘记密码？使用恢复码",
  "lock.recoveryBody": "输入你保存的恢复码。验证后，你可以设置新密码。",
  "lock.recoveryCode": "恢复码",
  "lock.recoveryCodePlaceholder": "输入恢复码",
  "lock.newPassword": "新密码",
  "lock.confirmPassword": "再次输入新密码",
  "lock.checking": "正在验证……",
  "lock.verifyAndSet": "验证并设置新密码",
  "lock.back": "返回密码输入",
  "lock.verifyError": "暂时无法验证密码，请稍后重试。",
  "lock.passwordMismatch": "两次输入的新密码不一致。",
  "lock.recoveryError": "暂时无法恢复密码，请稍后重试。",

  "settings.archive": "Ling 系统设置",
  "settings.close": "关闭系统设置",
  "settings.exit": "关闭设置",
  "settings.aria": "Ling 设置",
  "settings.logoAlt": "群心心理工作室标识",
  "settings.brandLine": "SETTINGS · 群心心理工作室",
  "settings.unsavedTitle": "还有未保存的设置",
  "settings.unsavedBody": "当前页面还有未保存的修改。若继续离开，这些修改会被放弃，并恢复为最近一次保存的内容。",
  "settings.discard": "放弃修改并继续",
  "settings.return": "返回当前页面",

  "room.you": "你",
  "room.noSession": "还没有会谈",
  "room.unfinishedBlocked": "这位咨询师还有一次尚未完成的咨询，请先继续或结束它。",
  "room.olderReadOnly": "只能继续与这位咨询师最近结束的会谈；更早的会谈仍可只读回看。",
  "room.closingNotice": "咨询结束后，我想对你说的话，会写进一封会谈后的信里，留在等待室底栏的「咨询师的信」中；完整会谈仍可在沙发区的「历史记录」回看。",
  "room.statusOther": "{name}正在另一场会谈中",
  "room.statusThinking": "{name}在想",
  "room.statusSpeaking": "{name}在说",
  "room.statusListening": "{name}在听",
  "room.statusError": "连接暂时中断，请检查设置",
  "room.attachmentEmpty": "{file} 中没有读取到文字。请移除该文件，或换一个文件后再发送。",
  "room.attachmentReadError": "没有成功读取附件。请重新选择，或先移除该附件再发送。",
  "room.attachmentUnsupported": "暂不支持 {file} 的格式。请选择图片、TXT、Markdown、PDF、DOC 或 DOCX 文件；PDF 和 Word 当前只保存文件记录，不读取正文。",
  "room.attachmentTooLarge": "{file} 超过 50 MB，无法添加。请选择更小的文件。",
  "room.pastedFileName": "粘贴的长文本.txt",
  "room.pasteNotice": "已将这次粘贴的约 {count} 字转为文本资料；可在发送前移除。",
  "room.start": "开始咨询",
  "room.backLobby": "返回等待室",
  "room.skipOpening": "跳过开场",
  "room.enterDirectly": "直接进入咨询",
  "room.skipClosing": "跳过收尾",
  "room.letterOpened": "来信已打开",
  "room.letterUnknown": "暂时无法确认这封信是否已经生成完成。",
  "room.reloadStatus": "重新读取状态",
  "room.backPrevious": "返回上一步",
  "room.aria": "{name}的咨询室",
  "room.closeError": "关闭咨询错误提示",
  "room.loadingMessages": "正在读取这次会谈的完整记录。读取完成前不会发送新消息。",
  "room.reload": "重新读取",
  "room.continueCurrent": "继续当前咨询",
  "room.confirmEnd": "确认结束",
  "room.endMessage": "确认后，本次咨询会结束并转为只读，不能再继续发送消息。Ling 会在后台整理这次会谈并准备咨询师来信；完整记录会保留在等待室的「历史记录」中。",
  "room.endTitle": "结束本次咨询？",
  "room.returnCheck": "返回检查",
  "room.clearAndStart": "清除并开始新咨询",
  "room.endAndStart": "结束当前咨询并新建",
  "room.newUnsentMessage": "当前咨询还没有发送任何内容。开始新咨询后，未发送的文字和附件将被清除，当前空会谈不会保留。",
  "room.newMixedMessage": "当前咨询将结束并进入后台整理。已发送的会谈内容会保留；尚未发送的文字和附件不会保留。",
  "room.newSentMessage": "当前咨询将结束并进入后台整理，已发送的会谈内容会保留。",
  "room.newTitle": "开始一场新咨询？",

  "composer.pendingAttachments": "待发送附件",
  "composer.removeAttachment": "移除附件 {name}",
  "composer.chooseFile": "选择附件文件",
  "composer.addAttachment": "添加附件",
  "composer.attachmentHelp": "选择照片、文档或文本",
  "composer.voice.startInput": "开始语音输入",
  "composer.voice.stopInput": "停止语音输入",
  "composer.voice.title": "语音输入",
  "composer.voice.stopDictation": "停止听写",
  "composer.voice.shortcutHint": "{shortcut} · 按一次开始或停止",
  "composer.voice.clickHint": "点击开始 · 可在设置中添加快捷键",
  "composer.input": "会谈输入框",
  "composer.endedPlaceholder": "本次咨询已结束。若要继续输入，请先选择“继续咨询”。",
  "composer.placeholder": "慢慢说，发生了什么？",
  "composer.ended": "已结束",
  "composer.wait": "等待",
  "composer.stop": "停止",
  "composer.send": "发送",

  "messages.stream": "消息流",
  "messages.startNew": "开始新会谈",
  "messages.avatar": "{name}头像",
  "messages.responding": "{name}正在回应",
  "messages.attachments": "消息附件",
  "messages.imageSent": "已发送给模型识别",
  "messages.notRead": "暂未读取正文",
  "messages.characterCount": "约 {count} 字",
  "messages.understanding": "{name}正在理解你的话",
  "messages.sendFailed": "发送没有完成",
  "messages.retry": "重试",

  "preparation.aria": "咨询结束后的整理进度",
  "preparation.heading": "咨询结束后的整理",
  "preparation.failed": "暂时没有完成",
  "preparation.working": "正在整理",
  "preparation.failedBody": "这次整理暂时没有完成，可以重新生成。",
  "preparation.workingBody": "Ling 正在整理这次咨询，并准备咨询师来信。你可以先返回等待室，处理会继续进行。",
  "preparation.retry": "重新整理这次咨询",

  "letter.cardAria": "咨询师的来信",
  "letter.from": "{name}的来信",
  "letter.ready": "已经写好了",
  "letter.failed": "生成失败",
  "letter.writing": "正在写",
  "letter.pendingBody": "{name}正在写信。你可以先返回等待室，写好后会收在底栏的「咨询师的信」里。",
  "letter.failedBody": "这封信没有生成完成，可以稍后重新生成。",
  "letter.readyBody": "来信已经准备好了。你可以现在打开，也可以之后再读。",
  "letter.progress": "咨询师正在写信，通常需要 1–3 分钟",
  "letter.open": "打开这封信",
  "letter.regenerate": "重新生成",
  "letter.readerAria": "{name}写给你的信",
  "letter.close": "关闭来信",
  "letter.title": "{name}写给你的一封信",

  "history.current": "当前会谈",
  "history.endingAria": "正在结束咨询",
  "history.with": "与{name}的会谈",
  "history.recheck": "重新检查状态",
  "history.resume": "继续咨询",
  "history.endingStatus": "正在保存会谈并确认结束状态，请稍等……",
  "history.loading": "正在读取这次会谈的完整记录。如果长时间没有完成，可以重新读取。",
  "history.reload": "重新读取会谈记录",

  "sidebar.roomActions": "咨询室操作",
  "sidebar.returnHint": "本次会谈会保留，稍后可继续。",
  "sidebar.continueSession": "继续本次咨询",
  "sidebar.endSession": "结束本次咨询",
  "sidebar.end": "结束",
  "sidebar.continueHint": "回到这次会谈继续交流。",
  "sidebar.endHint": "会谈记录会保留，并收到咨询师的一封信。",
  "stage.currentInfo": "当前会谈信息",
  "closing.options": "咨询结束后的选择",
  "closing.viewHistory": "查看历史记录",
  "closing.readLetter": "阅读咨询师的信",
  "arrival.aria": "进入咨询室",
  "arrival.continue": "继续进入咨询室",
  "arrival.showFull": "立即显示完整场记",
  "confirm.stay": "留在这里",
  "dialogue.next": "下一句",
  "dialogue.opening": "咨询开场",
  "dialogue.closing": "咨询收尾",
  "dialogue.counselor": "心理咨询师",
  "dialogue.wait": "请稍等……",
  "counselors.portraitAlt": "{name}咨询师形象",

  "session.ended": "已结束",
  "session.active": "进行中",
  "session.deleteConfirm": "删除会谈“{title}”？此操作会删除本机上的这场会谈记录，且不能撤销。",
  "session.navigation": "会谈导航",
  "session.tools": "会谈工具",
  "session.newAria": "结束当前咨询并与这位咨询师开始新会谈",
  "session.new": "新建会谈",
  "session.newHint": "结束当前咨询并开始新咨询",
  "session.recordsHint": "查看当前与历史会谈",
  "session.settingsHint": "调整模型与使用偏好",
  "session.settings": "设置",
  "session.localSessions": "本地会谈",
  "session.localSaved": "本地保存",
  "session.closeRecords": "关闭会谈记录",
  "session.noCurrent": "当前没有与这位咨询师进行中的会谈。",
  "session.historyCount": "历史会谈（{count}）",
  "session.searchAria": "搜索当前咨询师的历史会谈",
  "session.searchPlaceholder": "搜索与这位咨询师的历史会谈",
  "session.noOther": "还没有与这位咨询师的其他会谈",
  "session.noMatch": "没有找到匹配的历史会谈",
  "session.rename": "重命名",
  "session.renameInput": "重命名会谈",
  "session.delete": "删除",
  "session.actions": "会谈操作 {title}",
  "session.deleteAria": "删除会谈 {title}",

  "launch.model.progressLabel": "引导第二步，共三步",
  "launch.model.kicker": "模型接入",
  "launch.model.title": "连接模型服务",
  "launch.model.intro": "使用 API 服务，或连接在这台设备上运行的模型。",
  "launch.model.guideTitle": "怎样获得 API Key？",
  "launch.model.guideBody": "在 DeepSeek 开放平台注册或登录，进入“API Keys”创建密钥，复制后粘贴到下面。",
  "launch.model.openKeys": "打开 DeepSeek API Keys",
  "launch.model.keyPlaceholder": "粘贴 sk- 开头的 API Key",
  "launch.model.show": "显示",
  "launch.model.hide": "隐藏",
  "launch.model.configuredNote": "已自动使用 DeepSeek 官方地址与 DeepSeek V4 Flash 推荐配置。",
  "launch.model.actionsLabel": "模型连接操作",
  "launch.model.connecting": "正在连接……",
  "launch.model.connect": "连接并继续",
  "launch.model.skip": "暂时跳过",

  "settings.profile.languageTitle": "界面与咨询语言",
  "settings.profile.languageDescription": "切换后立即生效，并保存在这台设备上。",
  "settings.profile.save": "保存个人资料",

  "update.noticeLabel": "Ling 新版本提示",
  "update.dismiss": "暂时关闭新版本提示",
  "update.availableSuffix": "已发布",
  "update.manualInstall": "可以前往官网下载，新版本仍由你手动安装。",
  "update.openWebsite": "前往官网下载",

  "consent.fullTitle": "完整知情同意书",
  "consent.beforeCounseling": "进入咨询前",
  "consent.headerDescription": "导读与各章正文使用资料桌中的同一份内容，你可以逐页阅读后决定是否继续。",
  "consent.readingDirectory": "阅读目录",
  "consent.overview": "导读",
  "consent.startingInformation": "开始前说明",
  "consent.readingInformation": "阅读说明",
  "consent.introductionTitle": "开始之前，请完整了解这段 AI 心理咨询关系",
  "consent.introductionAside": "你可以按左侧目录逐章阅读，也可以随时暂不进入。资料桌中会一直保留同一份完整知情同意书。",
  "consent.resourceIntroTitle": "阅读说明与目录",
  "consent.directoryLabel": "完整知情同意书目录",
  "consent.previous": "上一页",
  "consent.next": "下一页",
  "consent.version": "版本",
  "consent.notNow": "暂不进入",
  "consent.agree": "同意并进入咨询",
  "consent.acknowledgement": "我已阅读并理解这份完整知情同意书。我知道 Ling 提供的是基于 AI 大语言模型的心理咨询，不能替代由具备专业资质的真人提供的心理咨询、心理治疗、精神科诊疗或危机救援；我可以暂不进入，也可以随时退出。我愿意继续。",
  "consent.sensitiveAcknowledgement": "我知道在 Ling 官方版本中，会谈记录默认保存在这台设备上，不会通过 Ling 自有服务器传输。使用本机模型时，相关内容不会离开这台设备；使用第三方模型 API 服务时，为生成回应和会谈后材料，必要内容会发送给我配置的模型服务商，并由对方按照其隐私政策处理。我同意按以上说明处理这些信息。",

  "crisis.title": "心理危机与安全支持",
  "crisis.directory": "心理危机与安全支持目录",
  "crisis.directoryLabel": "本页目录",
  "crisis.immediateTitle": "如果你担心自己或别人马上会受伤",
  "crisis.immediateBody": "请立刻告诉身边可信赖的人你在哪里，并联系所在地的紧急服务。中国大陆可拨打 110 或 120；如果无法自行拨号，请让身边的人代拨，或请他人陪同前往就近急诊。不要等待 Ling 或心理热线的回应。",
  "crisis.emergencyNumbers": "紧急服务号码",
  "crisis.situationsTitle": "如果现在真的很难熬",
  "crisis.situationsIntro": "这些做法只用于连接和等待现实帮助，不能替代紧急救援。不用全部做到；如果危险正在发生，直接回到上一页联系 110 或 120。",
  "crisis.moreActions": "更多做法",
  "crisis.contactsTitle": "中国大陆｜求助资源",
  "crisis.contactsNote": "点击号码不会自动拨出。Ling 不能外呼、定位、报警或派出救援；请使用可通话的设备自行拨打。",
  "crisis.noAnswerTitle": "如果没有接通，或危险仍在升级",
  "crisis.noAnswerBody": "不要反复等待心理热线。请改拨 110 或 120、请身边的人代拨，或请他人陪同前往就近急诊；不要自行驾车。心理援助热线提供真人支持，但不等同于现场紧急救援。",
  "crisis.otherRegionsTitle": "如果你不在中国大陆",
  "crisis.otherRegionsBody": "请联系所在地的紧急服务号码、心理危机热线或就近急诊。如果不确定应该联系什么，可以请身边可信赖的人协助查找并联系。选择英文界面并不表示这些中国大陆号码在你所在地可用。",
  "crisis.officialSource": "查看国家卫生健康委关于 12356 的说明",
  "crisis.limitTitle": "不要把 Ling 当作紧急服务",
  "crisis.limitBody": "Ling 不能持续监测你是否安全或是否掉线，也不能确认位置、拨号、报警、通知亲友或派出救援。遇到危险，不要等待 AI 回应：请直接联系现实中的人、紧急服务或就近医疗机构。",
  "crisis.limitEmergencyBody": "心理热线、文字陪伴、呼吸或感官练习都不能替代 110、120 和急诊。Ling 的任何回复也不代表已经完成专业风险评估。",

  "counselors.choose": "选择咨询师",
  "counselors.currentlyViewing": "正在了解",
  "counselors.activeSession": "有进行中的咨询",
  "counselors.book": "预约咨询",
  "counselors.aiBoundaryLabel": "查看 AI 咨询师说明",
  "counselors.aiBoundary": "她是 AI 咨询师，可提供心理支持，但不能替代专业心理咨询、精神科诊疗、医学诊断或危机干预。",
  "counselors.viewHeading": "她如何理解咨询",
  "counselors.workingHeading": "她如何与来访者工作",
  "counselors.topicsHeading": "她较常关注的议题",
  "counselors.sharedBeliefTitle": "Ling 咨询师共同相信",
  "counselors.sharedBelief1": "心理咨询师不是掌握答案的人，而是一面镜子。",
  "counselors.sharedBelief2": "咨询的过程，不是向外寻找某个现成的答案。",
  "counselors.sharedBelief3": "而是和你一起，探索内心尚未被看见和理解的部分，慢慢认识自己。",

  "resources.back": "返回资料目录",
  "resources.documentVersion": "文档版本",
  "resources.version": "版本",
  "resources.loading": "正在打开资料……",
  "resources.empty": "这份资料没有可显示的内容。",
  "resources.error": "资料读取失败，请稍后重试。",
  "resources.desk": "资料桌",
  "resources.studioMaterials": "工作室使用资料",
  "resources.footer": "使用帮助 · 安全支持 · 知情同意",
  "resources.view": "查看",

  "guide.title": "使用帮助",
  "guide.directory": "使用帮助目录",
  "guide.topicLabel": "使用帮助 · 按需查阅",
  "guide.note": "补充说明",
  "guide.return": "返回使用帮助目录"
} as const;

export type TranslationKey = keyof typeof zhCN;
